#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d I II III IV

bspc config border_width         0
# bspc config -n $(bspc query -N -n) border_width 0
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
# bspc config gapless_monocle      true
# bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# bspc config focused_border_color        "#6c71c4"
# bspc config normal_border_color         "#073642"
# bspc config active_border_color         "#073642"

sh ~/.screenlayout/monitor.sh &
~/.config/polybar/launch.sh &
/usr/bin/dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nitrogen --restore &
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
picom -CGb &
nm-applet --indicator &
xsetroot -cursor_name left_ptr &
